[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_API_BASE_URL"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Only needed if you have custom headers or redirects
# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"